---
name: RPM repositories

on:
  workflow_dispatch:
  schedule:
    - cron: "30 8 * * 1-5"

permissions:
  contents: read

jobs:
  Sync:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update
        run: ./hack/update-known-rpm-repositories.sh

      - name: Pull request
        id: pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            data/known_rpm_repositories.yml
          branch: ci/update-rpm-repositories
          commit-message: Update list of known RPM repositories
          reviewers: |
            lcarva
          sign-commits: true
          signoff: true
          title: Update list of known RPM repositories
